blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/FlycktCoding/cli-new-express-app/discussions
    about: Please ask questions and get support in Discussions.
