blank_issues_enabled: false
contact_links:
  - name: 💬 Github message
    url: https://github.com/Ludvigpbf
    about: Ask questions or give feedback about this project
  - name: 📧 Email
    url: mailto:"contact@flycktcoding.com"
    about: Ask questions or give feedback about this project