import inquirer from "inquirer";

/**
 * 
 */

export const askTesting = async () => {
  return await inquirer.prompt([
    {
      type: "confirm",
      name: "testing",
      message: "Do you want to include testing in your project?",
      default: true,
    },
    {
      type: "checkbox",
      name: "testingOptions",
      message: "Select testing libraries",
      choices: [
        "jest",
        "mocha",
        "chai",
        "jasmine",
        "none",
        new inquirer.Separator("--- End of list ---"),
      ],
      when: ({ testing }) => testing,
    },
    {
      type: "checkbox",
      name: "jestOptions",
      message: "Select Jest options",
      choices: [
        "jest",
        "jest-cli",
        "jest-dom",
        "jest-environment-jsdom",
        "jest-environment-node",
        "jest-extended",
        "jest-junit",
        "jest-preset-angular",
        "jest-preset-mongoose",
        "jest-puppeteer",
        "jest-runner-eslint",
        "jest-runner-mocha",
        "jest-runner-tslint",
        "jest-serializer",
        "jest-transform-stub",
        "jest-watch-typeahead",
        "jest-worker",
        "jest-coverage-badge",
        "none",
        new inquirer.Separator("--- End of list ---"),
      ],
      when: ({ testingOptions }) => testingOptions.includes("jest"),
    },
    {
      type: "checkbox",
      name: "mochaOptions",
      message: "Select Mocha options",
      choices: [
        "mocha",
        "mocha-parallel-tests",
        "mocha-sonarqube-reporter",
        "mocha-multi-reporters",
        "mocha-junit-reporter",
        "mocha-remote-debug",
        "none",
        new inquirer.Separator("--- End of list ---"),
      ],
      when: ({ testingOptions }) => testingOptions.includes("mocha"),
    },
    {
      type: "checkbox",
      name: "chaiOptions",
      message: "Select Chai options",
      choices: [
        "chai",
        "chai-as-promised",
        "chai-asserttype",
        "chai-arrays",
        "chai-change",
        "chai-datetime",
        "chai-diff",
        "chai-exclude",
        "chai-fs",
        "chai-generator",
        "chai-http",
        "chai-jquery",
        "chai-json-schema",
        "chai-like",
        "chai-match-pattern",
        "chai-moment",
        "chai-namespace",
        "chai-numbers",
        "chai-objects",
        "chai-omit",
        "chai-properties",
        "chai-roughly",
        "chai-shallow-deep-equal",
        "chai-sinon",
        "chai-smoothie",
        "chai-spies",
        "chai-string",
        "chai-subset",
        "chai-things",
        "chai-url",
        "chai-webdriver",
        "chai-xml",
        "none",
        new inquirer.Separator("--- End of list ---"),
      ],
      when: ({ testingOptions }) => testingOptions.includes("chai"),
    },
    {
      type: "checkbox",
      name: "jasmineOptions",
      message: "Select Jasmine options",
      choices: [
        "jasmine",
        "jasmine-core",
        "jasmine-spec-reporter",
        "jasmine-expect",
        "jasmine-ajax",
        "jasmine-jquery",
        "jasmine-ts",
        "jasmine-marbles",
        "jasmine-pit",
        "jasmine-enzyme",
        "jasmine-check",
        "jasmine-async",
        "jasmine-diff",
        "jasmine-fixture",
        "jasmine-sinon",
        "jasmine-spy",
        "none",
        new inquirer.Separator("--- End of list ---"),
      ],
      when: ({ testingOptions }) => testingOptions.includes("jasmine"),
    },  
]);
};
