name: "🐞 Bug Report"
description: "Report a reproducible bug in the project."
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ludvigpbf
body:
  - type: markdown
    attributes:
      value: "### Type: Bug"
  - type: markdown
    attributes:
      value: "### Status: Backlog"
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill in the details below."

  - type: dropdown
    id: version
    attributes:
      label: "Version"
      description: "Which version of the CLI are you using?"
      options: 
        - "V1"
        - "V2"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: "Branch"
      description: "Which branch is the bug on?"
      options: 
        - "main"
        - "prompt"
        - "help"
        - "template"
        - "fetaure"
        - "config"
      default: 0
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Describe the bug in detail."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the issue."
      placeholder: |
        1. Run `cli-new-express-app`
        2. Select options X, Y, Z
        3. See error...
    validations:
      required: true
