name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees:
  - ludvigpbf
body:
  - type: dropdown
    id: type
    attributes:
      label: "Type"
      description: "Issue type"
      options:
        - "Feature"
        - "Bug"
        - "Refactor"
        - "Documentation"
        - "Question"
      default: 4
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "Describe your question in detail."
      placeholder: "Write your question here..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Provide any relevant information, links, or examples."
      placeholder: "Any additional context..."
  - type: dropdown
    id: urgency
    attributes:
      label: "Urgency Level"
      description: "How urgent is this question?"
      options:
        - "Low - Just curious"
        - "Medium - Need an answer soon"
        - "High - Blocking my progress"
    validations:
      required: true
